apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: kube-news
build:
  artifacts:
  - image: fabricioveronez/kube-news
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
