# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
        - name: postgre
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "Kube#123"
          - name: POSTGRES_USER
            value: "kubenews"
          - name: POSTGRES_DB
            value: "kubenews"
---

# Deploy do serviço parecido com loadbalance que faz o balanceamento dos pods logicos 
# Nesse caso está sendo usado TargetPort, mas se fosse na AWS, seria um LoadBalancer por exemplo

apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432 
    targetPort: 5432
---

# Deploy da aplicação

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 20
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews  
    spec:
      containers:
      - name: kubenews
        image: teusvarela/kube-news:v1
        env:
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "kubenews"
        - name: DB_PASSWORD
          value: "Kube#123"
        - name: DB_HOST
          value: "postgre"      
---


# Deploy do serviço parecido com loadbalance que faz o balanceamento dos pods logicos 
# Nesse caso está sendo usado TargetPort e Nodeport, mas se fosse na AWS, seria um LoadBalancer por exemplo

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
